//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoatVeOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        [Display(Name = "Mã Khách Hàng")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public int MaKH { get; set; }
        [Display(Name = "Họ tên")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string HoTen { get; set; }
        [Display(Name = "Tài khoản")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật khẩu")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string MatKhau { get; set; }
        [Display(Name = "Email")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string Email { get; set; }
        [Display(Name = "Địa chỉ")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string DiaChi { get; set; }
        [Display(Name = "Số điện thoại")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string DienThoai { get; set; }
        [Display(Name = "Giới tính")] // thuoc tinh display
        [Required(ErrorMessage = "{0} không để trống!")]
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
