//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoatVeOnline.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.DiaDiems = new HashSet<DiaDiem>();
        }
        public int MaVe { get; set; }
        public string TenVe { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
        public Nullable<int> MaSuKien { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaDiem> DiaDiems { get; set; }
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual SuKien SuKien { get; set; }
    }
}
